services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      PORT: 7473
    ports:
      - "7473:7473"

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: "http://backend:7473"
    ports:
      - "7474:7474"
